title: The Politics of Digital Platforms
description: "A Stakeholder Forum by Jeffrey Moro"
baseurl: "/611-digital-forum" # the subpath of your site, e.g. /blog
url: "https://jeffreymoro.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jeffreymoro
github_username:  jeffreymoro

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css/_scss
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/